name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Kör CI/CD varje gång vi pushar till main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # Justera om du använder en annan .NET-version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ShayanCICD
          environment_name: ShayanCICD-env
          version_label: ${{ github.run_number }}
          region: eu-north-1
          deployment_package: ./publish
