name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ShayanCICD/ShayanCICD/ShayanCICD.csproj

      - name: Build application
        run: dotnet build ShayanCICD/ShayanCICD/ShayanCICD.csproj --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish ShayanCICD/ShayanCICD/ShayanCICD.csproj -c Release -o ./publish

      - name: Create deployment package (ZIP)
        run: cd publish && zip -r ../deploy.zip .

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ShayanCICD
          environment_name: ShayanCICD-env
          version_label: ${{ github.run_number }}
          region: eu-north-1
          deployment_package: deploy.zip
